# health_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# A model for the hospital/clinic, which acts as a tenant for data segregation.
class Hospital(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

# We create a Custom User model. This is the modern, recommended Django approach.
# It lets us add fields directly to the user, simplifying everything.
class User(AbstractUser):
    class Role(models.TextChoices):
        HOSPITAL_ADMIN = "HOSPITAL_ADMIN", "Hospital Admin"
        DOCTOR = "DOCTOR", "Doctor"
        # We can add a SUPER_ADMIN role later for the platform manager.

    role = models.CharField(max_length=50, choices=Role.choices)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, null=True, blank=True)

# We need to tell Django to use THIS User model instead of its default one.
# Add this line to your config/settings.py at the bottom.
# AUTH_USER_MODEL = 'health_app.User'


# This model represents one patient's blood test data (one row from the CSV).
class PatientRecord(models.Model):
    patient_identifier = models.CharField(max_length=100, help_text="A unique ID for the patient (e.g., P001, MRN-456)")
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE, related_name="patient_records")
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="uploaded_records")

    # Blood Test Markers
    glucose = models.FloatField(null=True, blank=True)
    hba1c = models.FloatField(null=True, blank=True)
    total_cholesterol = models.FloatField(null=True, blank=True)
    ldl = models.FloatField(null=True, blank=True)
    hdl = models.FloatField(null=True, blank=True)
    triglycerides = models.FloatField(null=True, blank=True)
    alt = models.FloatField(null=True, blank=True)
    ast = models.FloatField(null=True, blank=True)
    creatinine = models.FloatField(null=True, blank=True)
    urea = models.FloatField(null=True, blank=True)
    crp = models.FloatField(null=True, blank=True)
    wbc = models.FloatField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # A patient within a single hospital should be unique.
        unique_together = ('hospital', 'patient_identifier')

    def __str__(self):
        return f"Record for {self.patient_identifier} at {self.hospital.name}"

# This model stores the AI analysis and the doctor's review.
class RiskAssessment(models.Model):
    class Status(models.TextChoices):
        PENDING_REVIEW = "PENDING_REVIEW", "Pending Review"
        REVIEWED = "REVIEWED", "Reviewed"
        NEEDS_INFO = "NEEDS_INFO", "Needs More Info"

    patient_record = models.OneToOneField(PatientRecord, on_delete=models.CASCADE, related_name="assessment")
    ai_generated_report = models.TextField(help_text="The risk assessment report generated by the AI.")
    doctor_comments = models.TextField(blank=True, null=True, help_text="Comments and final assessment by the doctor.")
    status = models.CharField(max_length=50, choices=Status.choices, default=Status.PENDING_REVIEW)
    assigned_doctor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="assigned_assessments")
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="reviewed_assessments")
    reviewed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Assessment for {self.patient_record.patient_identifier} - {self.status}"